[general]
working_directory = "C:\\Users\\dimitri\\Desktop"

[window]
dimensions = { columns = 140, lines = 30 }

[font]
normal = { family = "Iosevka Fixed", style = "Regular" }
size = 14

[cursor]
unfocused_hollow = false

[terminal]
shell = "cmd"
